In [1]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
random_array = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose the array)
transposed_array = random_array.T

random_array, transposed_array


(array([[11, 76, 25],
        [57, 98, 73],
        [66, 84, 39]]),
 array([[11, 57, 66],
        [76, 98, 84],
        [25, 73, 39]]))

In [2]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
# Generate a 1D NumPy array with 10 elements
one_d_array = np.arange(1, 11)

# Reshape into a 2x5 array
array_2x5 = one_d_array.reshape(2, 5)

# Reshape into a 5x2 array
array_5x2 = one_d_array.reshape(5, 2)

one_d_array, array_2x5, array_5x2


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]))

In [3]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
# Create a 4x4 NumPy array with random float values
random_float_array = np.random.rand(4, 4)

# Add a border of zeros around it, resulting in a 6x6 array
bordered_array = np.pad(random_float_array, pad_width=1, mode='constant', constant_values=0)

random_float_array, bordered_array


(array([[0.8058738 , 0.31611817, 0.10849822, 0.41898499],
        [0.8109959 , 0.7439336 , 0.0409483 , 0.87285028],
        [0.54384292, 0.11736599, 0.7565609 , 0.33582201],
        [0.39582613, 0.2007095 , 0.45534215, 0.42088037]]),
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.8058738 , 0.31611817, 0.10849822, 0.41898499,
         0.        ],
        [0.        , 0.8109959 , 0.7439336 , 0.0409483 , 0.87285028,
         0.        ],
        [0.        , 0.54384292, 0.11736599, 0.7565609 , 0.33582201,
         0.        ],
        [0.        , 0.39582613, 0.2007095 , 0.45534215, 0.42088037,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]))

In [4]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.
# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply case transformations
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)

string_array, uppercase_array, lowercase_array, titlecase_array


(array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6'),
 array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'))

In [5]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
# Generate a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy'])

# Insert a space between each character of every word
spaced_array = np.char.join(' ', words_array)

words_array, spaced_array


(array(['hello', 'world', 'numpy'], dtype='<U5'),
 array(['h e l l o', 'w o r l d', 'n u m p y'], dtype='<U9'))

In [6]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[6, 5, 4], [3, 2, 1]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

array1, array2, addition, subtraction, multiplication, division


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[6, 5, 4],
        [3, 2, 1]]),
 array([[7, 7, 7],
        [7, 7, 7]]),
 array([[-5, -3, -1],
        [ 1,  3,  5]]),
 array([[ 6, 10, 12],
        [12, 10,  6]]),
 array([[0.16666667, 0.4       , 0.75      ],
        [1.33333333, 2.5       , 6.        ]]))

In [7]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

identity_matrix, diagonal_elements


(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 array([1., 1., 1., 1., 1.]))

In [8]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
# Function to check for prime numbers
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = random_integers[np.vectorize(is_prime)(random_integers)]

random_integers, prime_numbers


(array([399, 881, 801, 432, 343, 238, 310, 686, 388, 911, 337, 144, 437,
        769, 903,   2, 809, 173, 286, 702, 552, 242, 501, 412, 430, 904,
        586, 650, 918, 644, 135, 164, 729, 413, 691,  83, 392, 680, 155,
        856, 327, 280, 110, 849, 766, 403, 746, 619, 832, 137, 198, 976,
        843, 840, 901, 190, 674, 947, 344, 733, 823, 910, 571, 287, 638,
        747, 210, 925, 254,   2, 662, 669, 369,  10, 129, 996, 971, 888,
        707, 580, 629, 325, 941,  62, 984, 175, 401,   0, 649, 465, 950,
        344, 859, 217, 640, 201, 677, 370, 663, 716]),
 array([881, 911, 337, 769,   2, 809, 173, 691,  83, 619, 137, 947, 733,
        823, 571,   2, 971, 941, 401, 859, 677]))

In [10]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
import numpy as np

# Generate a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(15, 35, size=30)  # Temperatures between 15 and 35 degrees Celsius

# Calculate weekly averages (assuming weeks are 7 days each)
weekly_averages = daily_temperatures.reshape(4, 7).mean(axis=1)

print("Daily Temperatures:", daily_temperatures)
print("Weekly Averages:", weekly_averages)


ValueError: cannot reshape array of size 30 into shape (4,7)